name: Test Flutter apps
on: 
  pull_request:
    branches: ['main']
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Flutter action
        uses: subosito/flutter-action@v2.8.0
      - name: Run `flutter test`
        run: flutter test
